# Generated by Django 5.1.4 on 2026-06-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='taskerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='taskerprofile',
            name='tier',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='taskerprofile',
            name='trust_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
