# Generated by Django 5.1.4 on 2026-06-29 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrc_front', models.ImageField(blank=True, null=True, upload_to='verification/nrc/')),
                ('nrc_back', models.ImageField(blank=True, null=True, upload_to='verification/nrc/')),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='verification/face/')),
                ('promotion_video', models.FileField(blank=True, null=True, upload_to='verification/video/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=255)),
                ('verification_status', models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_SUBMITTED', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
