# Generated by Django 5.1.4 on 2026-06-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneotp',
            name='user',
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='phone_number',
            field=models.CharField(db_index=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
